// @ts-check

const fs = require('fs');
const path = require('path');

const {hasEnglishDoc, isEnglishBuild} = require('./scripts/english-docs');
const splitDocSourceIds = new Set(require('./src/generated/splitDocSourceIds.json'));

const docsDir = path.join(__dirname, 'docs_cn');

function resolveSplitDocId(docId) {
  return splitDocSourceIds.has(docId) ? `${docId}/README` : docId;
}

function shouldIncludeDoc(docId) {
  return !isEnglishBuild() || hasEnglishDoc(docId);
}

function hasSourceDoc(docId) {
  const resolvedDocId = resolveSplitDocId(docId);

  return ['.md', '.mdx'].some((extension) =>
    fs.existsSync(path.join(docsDir, `${resolvedDocId}${extension}`)),
  );
}

const localizedDoc = (label, id, suffix = '') =>
  hasSourceDoc(id) && shouldIncludeDoc(resolveSplitDocId(id))
    ? { type: 'doc', label, id: resolveSplitDocId(id) }
    : undefined;

const existingDocsOnly = (items) => items.filter(Boolean);

const productSpecDoc = (label, id, suffix = '') => {
  const wikiDoc = localizedDoc(
    `Wiki 教程${suffix}`,
    id.replace(/\/README$/, '/wiki-tutorial'),
  );

  // 没有 Wiki 教程时，和「终端」等 autogenerated 分类保持一致：渲染成扁平文档链接，
  // 而不是只含产品规格书的可展开分类（避免出现「AI边缘工作站 > AI边缘工作站」这种重复层级）。
  if (!wikiDoc) {
    return { type: 'doc', label: `${label}${suffix}`, id };
  }

  // 有 Wiki 教程时渲染成可展开分类：产品规格书作为分类首页链接，Wiki 教程作为子项。
  return {
    type: 'category',
    label: `${label}${suffix}`,
    collapsed: true,
    link: { type: 'doc', id },
    items: [wikiDoc],
  };
};

const localizedProductSpecDoc = (label, id, suffix = '') =>
  shouldIncludeDoc(id) ? productSpecDoc(label, id, suffix) : undefined;

const topCategory = ({ label, section, items }) => ({
  type: 'category',
  label,
  link: {
    type: 'doc',
    id: `${section}/README`,
  },
  className: `sidebar-section-top sidebar-section-${section}`,
  collapsed: true,
  items,
});

const sectionItems = (dirName, products) => [
  { type: 'autogenerated', dirName },
  ...products,
];

const sharedProducts = {
  aiotSolutions: existingDocsOnly([
    localizedProductSpecDoc('AI边缘工作站', 'terminal/ai-edge-workstation/README', '\u200B'),
    localizedProductSpecDoc('RK3576 数据采集网关', 'terminal/rk3576-data-acquisition-gateway/README', '\u200B'),
    localizedProductSpecDoc('8英寸平板', 'terminal/eight-inch-tablet/README', '\u200B'),
    localizedProductSpecDoc('10.6英寸平板', 'terminal/ten-six-inch-tablet/README', '\u200B'),
    localizedProductSpecDoc('11英寸平板', 'terminal/eleven-inch-tablet/README', '\u200B'),
    localizedProductSpecDoc('RK3568 数据采集网关', 'terminal/rk3568-data-acquisition-gateway/README', '\u200B'),
    localizedProductSpecDoc('工控屏', 'terminal/industrial-panel/README', '\u200B'),
    localizedProductSpecDoc('拼接屏处理器', 'terminal/video-wall-processor/README', '\u200B'),
  ]),
  openHarmony: existingDocsOnly([
    localizedProductSpecDoc('RK3568 主板', 'main-board/rk3568-main-board/README', '\u200C'),
    localizedProductSpecDoc('RK3576 数据采集网关', 'terminal/rk3576-data-acquisition-gateway/README', '\u200C'),
    localizedProductSpecDoc('RK3568 工业控制主板', 'main-board/rk3568-industrial-control-main-board/README', '\u200C'),
    localizedProductSpecDoc('RK3576 工业控制主板', 'main-board/rk3576-industrial-control-main-board/README', '\u200C'),
    localizedProductSpecDoc('8英寸平板', 'terminal/eight-inch-tablet/README', '\u200C'),
    localizedProductSpecDoc('10.6英寸平板', 'terminal/ten-six-inch-tablet/README', '\u200C'),
    localizedProductSpecDoc('11英寸平板', 'terminal/eleven-inch-tablet/README', '\u200C'),
    localizedProductSpecDoc('RK3568 数据采集网关', 'terminal/rk3568-data-acquisition-gateway/README', '\u200C'),
    localizedProductSpecDoc('RK3588 工业主板', 'main-board/rk3588-industrial-main-board/README', '\u200C'),
    localizedProductSpecDoc('RK3576 商业显示主板', 'main-board/rk3576-commercial-display-main-board/README', '\u200C'),
    localizedProductSpecDoc('工控屏', 'terminal/industrial-panel/README', '\u200C'),
    localizedProductSpecDoc('RK3588 主板', 'main-board/rk3588-main-board/README', '\u200C'),
    localizedProductSpecDoc('拼接屏处理器', 'terminal/video-wall-processor/README', '\u200C'),
  ]),
  mineHarmony: existingDocsOnly([
    localizedProductSpecDoc('RK3568 主板', 'main-board/rk3568-main-board/README', '\u200D'),
    localizedProductSpecDoc('RK3568 工业控制主板', 'main-board/rk3568-industrial-control-main-board/README', '\u200D'),
    localizedProductSpecDoc('RK3576 工业控制主板', 'main-board/rk3576-industrial-control-main-board/README', '\u200D'),
    localizedProductSpecDoc('8英寸平板', 'terminal/eight-inch-tablet/README', '\u200D'),
    localizedProductSpecDoc('11英寸平板', 'terminal/eleven-inch-tablet/README', '\u200D'),
    localizedProductSpecDoc('RK3568 数据采集网关', 'terminal/rk3568-data-acquisition-gateway/README', '\u200D'),
    localizedProductSpecDoc('RK3588 工业主板', 'main-board/rk3588-industrial-main-board/README', '\u200D'),
    localizedProductSpecDoc('工控屏', 'terminal/industrial-panel/README', '\u200D'),
  ]),
};

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    { type: 'doc', id: 'README', className: 'sidebar-docs-index-hidden' },
    topCategory({
      label: '核心板',
      section: 'core-board',
      items: [{ type: 'autogenerated', dirName: 'core-board' }],
    }),
    topCategory({
      label: '主板',
      section: 'main-board',
      items: [{ type: 'autogenerated', dirName: 'main-board' }],
    }),
    topCategory({
      label: '终端',
      section: 'terminal',
      items: [{ type: 'autogenerated', dirName: 'terminal' }],
    }),
    topCategory({
      label: 'AIOT解决方案',
      section: 'aiot-solutions',
      items: sectionItems('aiot-solutions', sharedProducts.aiotSolutions),
    }),
    topCategory({
      label: 'OpenHarmony',
      section: 'openharmony',
      items: sectionItems('openharmony', sharedProducts.openHarmony),
    }),
    topCategory({
      label: 'MineHarmony',
      section: 'mineharmony',
      items: sectionItems('mineharmony', sharedProducts.mineHarmony),
    }),
    topCategory({
      label: '其他',
      section: 'reference',
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    }),
  ],
};

module.exports = sidebars;
