// @ts-check

const fs = require('fs');
const path = require('path');

const {hasEnglishDoc, isEnglishBuild} = require('./scripts/english-docs');

const docsDir = path.join(__dirname, 'docs_cn');

function shouldIncludeDoc(docId) {
  return !isEnglishBuild() || hasEnglishDoc(docId);
}

function hasSourceDoc(docId) {
  return ['.md', '.mdx'].some((extension) =>
    fs.existsSync(path.join(docsDir, `${docId}${extension}`)),
  );
}

const localizedDoc = (label, id, suffix = '') =>
  hasSourceDoc(id) && shouldIncludeDoc(id) ? { type: 'doc', label, id } : undefined;

const existingDocsOnly = (items) => items.filter(Boolean);

const productSpecDoc = (label, id, suffix = '') => ({
  type: 'category',
  label: `${label}${suffix}`,
  collapsed: true,
  items: existingDocsOnly([
    {
      type: 'doc',
      id,
    },
    localizedDoc(
      `Wiki 教程${suffix}`,
      id.replace(/\/product-specification$/, '/wiki-tutorial'),
    ),
  ]),
});

const localizedProductSpecDoc = (label, id, suffix = '') =>
  shouldIncludeDoc(id) ? productSpecDoc(label, id, suffix) : undefined;

const topCategory = ({ label, section, items }) => ({
  type: 'category',
  label,
  className: `sidebar-section-top sidebar-section-${section}`,
  collapsed: true,
  items,
});

const sectionItems = (dirName, products) => [
  { type: 'autogenerated', dirName },
  ...products,
];

const sharedProducts = {
  aiotSolutions: existingDocsOnly([
    localizedProductSpecDoc('AI边缘工作站', 'terminal/ai-edge-workstation/product-specification', '\u200B'),
    localizedProductSpecDoc('RK3576 数据采集网关', 'terminal/rk3576-data-acquisition-gateway/product-specification', '\u200B'),
    localizedProductSpecDoc('8英寸平板', 'terminal/eight-inch-tablet/product-specification', '\u200B'),
    localizedProductSpecDoc('10.6英寸平板', 'terminal/ten-six-inch-tablet/product-specification', '\u200B'),
    localizedProductSpecDoc('11英寸平板', 'terminal/eleven-inch-tablet/product-specification', '\u200B'),
    localizedProductSpecDoc('RK3568 数据采集网关', 'terminal/rk3568-data-acquisition-gateway/product-specification', '\u200B'),
    localizedProductSpecDoc('工控屏', 'terminal/industrial-panel/product-specification', '\u200B'),
    localizedProductSpecDoc('拼接屏处理器', 'terminal/video-wall-processor/product-specification', '\u200B'),
  ]),
  openHarmony: existingDocsOnly([
    localizedProductSpecDoc('RK3568 主板', 'main-board/rk3568-main-board/product-specification', '\u200C'),
    localizedProductSpecDoc('RK3576 数据采集网关', 'terminal/rk3576-data-acquisition-gateway/product-specification', '\u200C'),
    localizedProductSpecDoc('RK3568 工业控制主板', 'main-board/rk3568-industrial-control-main-board/product-specification', '\u200C'),
    localizedProductSpecDoc('RK3576 工业控制主板', 'main-board/rk3576-industrial-control-main-board/product-specification', '\u200C'),
    localizedProductSpecDoc('8英寸平板', 'terminal/eight-inch-tablet/product-specification', '\u200C'),
    localizedProductSpecDoc('10.6英寸平板', 'terminal/ten-six-inch-tablet/product-specification', '\u200C'),
    localizedProductSpecDoc('11英寸平板', 'terminal/eleven-inch-tablet/product-specification', '\u200C'),
    localizedProductSpecDoc('RK3568 数据采集网关', 'terminal/rk3568-data-acquisition-gateway/product-specification', '\u200C'),
    localizedProductSpecDoc('RK3588 工业主板', 'main-board/rk3588-industrial-main-board/product-specification', '\u200C'),
    localizedProductSpecDoc('RK3576 商业显示主板', 'main-board/rk3576-commercial-display-main-board/product-specification', '\u200C'),
    localizedProductSpecDoc('工控屏', 'terminal/industrial-panel/product-specification', '\u200C'),
    localizedProductSpecDoc('RK3588 主板', 'main-board/rk3588-main-board/product-specification', '\u200C'),
    localizedProductSpecDoc('拼接屏处理器', 'terminal/video-wall-processor/product-specification', '\u200C'),
  ]),
  mineHarmony: existingDocsOnly([
    localizedProductSpecDoc('RK3568 主板', 'main-board/rk3568-main-board/product-specification', '\u200D'),
    localizedProductSpecDoc('RK3568 工业控制主板', 'main-board/rk3568-industrial-control-main-board/product-specification', '\u200D'),
    localizedProductSpecDoc('RK3576 工业控制主板', 'main-board/rk3576-industrial-control-main-board/product-specification', '\u200D'),
    localizedProductSpecDoc('8英寸平板', 'terminal/eight-inch-tablet/product-specification', '\u200D'),
    localizedProductSpecDoc('11英寸平板', 'terminal/eleven-inch-tablet/product-specification', '\u200D'),
    localizedProductSpecDoc('RK3568 数据采集网关', 'terminal/rk3568-data-acquisition-gateway/product-specification', '\u200D'),
    localizedProductSpecDoc('RK3588 工业主板', 'main-board/rk3588-industrial-main-board/product-specification', '\u200D'),
    localizedProductSpecDoc('工控屏', 'terminal/industrial-panel/product-specification', '\u200D'),
  ]),
};

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    topCategory({
      label: '核心板',
      section: 'core-board',
      items: [{ type: 'autogenerated', dirName: 'core-board' }],
    }),
    topCategory({
      label: '主板',
      section: 'main-board',
      items: [{ type: 'autogenerated', dirName: 'main-board' }],
    }),
    topCategory({
      label: '终端',
      section: 'terminal',
      items: [{ type: 'autogenerated', dirName: 'terminal' }],
    }),
    topCategory({
      label: 'AIOT解决方案',
      section: 'aiot-solutions',
      items: sectionItems('aiot-solutions', sharedProducts.aiotSolutions),
    }),
    topCategory({
      label: 'OpenHarmony',
      section: 'openharmony',
      items: sectionItems('openharmony', sharedProducts.openHarmony),
    }),
    topCategory({
      label: 'MineHarmony',
      section: 'mineharmony',
      items: sectionItems('mineharmony', sharedProducts.mineHarmony),
    }),
    topCategory({
      label: '其他',
      section: 'reference',
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    }),
  ],
};

module.exports = sidebars;
