// @ts-check

const fs = require('fs');
const path = require('path');
const {isEnglishBuild} = require('./scripts/english-docs');

const topCategory = ({ label, section, items, hidden = false }) => ({
  type: 'category',
  label,
  link: {
    type: 'doc',
    id: `${section}/README`,
  },
  className: `sidebar-section-top sidebar-section-${section}${
    hidden ? ' sidebar-section-hidden' : ''
  }`,
  collapsed: true,
  items,
});

function isTopCategoryHidden(section) {
  const docsRoot = isEnglishBuild()
    ? path.join(
        __dirname,
        'docs_en',
        'en',
        'docusaurus-plugin-content-docs',
        'current',
      )
    : path.join(__dirname, 'docs_cn');
  const readmePath = path.join(docsRoot, section, 'README.md');

  if (!fs.existsSync(readmePath)) {
    return false;
  }

  const source = fs.readFileSync(readmePath, 'utf8');
  const frontMatter = source.match(/^---\r?\n([\s\S]*?)\r?\n---/);

  return /^hide_from_sidebar:\s*true\s*$/m.test(frontMatter?.[1] || '');
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    { type: 'doc', id: 'README', className: 'sidebar-docs-index-hidden' },
    topCategory({
      label: '核心板',
      section: 'core-board',
      items: [{ type: 'autogenerated', dirName: 'core-board' }],
    }),
    topCategory({
      label: '主板',
      section: 'main-board',
      items: [{ type: 'autogenerated', dirName: 'main-board' }],
    }),
    topCategory({
      label: '终端',
      section: 'terminal',
      items: [{ type: 'autogenerated', dirName: 'terminal' }],
    }),
    topCategory({
      label: 'AIOT解决方案',
      section: 'aiot-solutions',
      items: [{ type: 'autogenerated', dirName: 'aiot-solutions' }],
      hidden: isTopCategoryHidden('aiot-solutions'),
    }),
    topCategory({
      label: 'OpenHarmony',
      section: 'openharmony',
      items: [{ type: 'autogenerated', dirName: 'openharmony' }],
    }),
    topCategory({
      label: 'MineHarmony',
      section: 'mineharmony',
      items: [{ type: 'autogenerated', dirName: 'mineharmony' }],
    }),
    topCategory({
      label: '其他',
      section: 'reference',
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    }),
  ],
};

module.exports = sidebars;
